server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/training524?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: 20011216
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: 127.0.0.1

# 公共配置 与profiles选择无关
mybatis:
  type-aliases-package: com.example.training524.dao.entity
  mapper-locations: classpath:mapper/*.xml
  # 开启MyBatis的二级缓存
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true